version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8888:8888"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: vfarm_db
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
