services:
  postgres:
    image: postgres:latest
    container_name: vfarm-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: vfarmadmin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: userdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
